### ISSUE TITLE
EPIC: MIGRATION MASTER PLAN Deprecate the legacy system

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#104]
Well - when we move to V2 we might actually have some users who are used to V1.  I think we have the PDF download in V2, which I think is really the main value prop of V1.  Wondering if maybe we need something like a 'looking for the old version?' button.  Or maybe we don't maintain legacy at all.

**Comment by michiQ** [comment]
I've been using the qa version on desktop and it's fine - its just a little wide, but I think that's ok.  It works.  So i'm going to move this one to backlog. I think what we might want to do in the future is think about autosizing for desktop so it's not so wide on the screen, but that's not a priority.  Moving this one to backlog. Oh and the PDF is working - just taking a while and we have a card for dealing with that. so backlog we go....

**Comment by michiQ** [comment]
So we are going to  have the the current version go to about.yadaguru.com which will be the marketing page. a Yadaguru search will go directly to the yadaguru.com which is the mobile app.  so will www.yadaguru.com.   The  current site will go to legacy.yadaguru.com and have a link to the new marketing site and the app site.   We will have to do a gradual takedown of the legacy site - maybe post a date and an announcement and then eventually take it down.

**Comment by michiQ** [comment]
Step1: Creating now:
 - DONE Create New Marketing site in something (wix, google sites, wordpress)
-  DONE Connect to  about.yadaguru.com

Step 2: Then:
-  DONE Create a notice/button  'hey we are moving to the new app' on the current site to the about.yadaguru.com site
-  Update version 2 mobile app 'about' section with a link to the about.yadaguru.com


Step 3. 
- Sync with Code for Philly on how this will all work in their AWS

Step 4: MIGRATION DAY Then: On the same Day
- move the current site to legacy.yadaguru.com
 - replace with version 2 on yadaguru.com

**Comment by michiQ** [comment]
First draft of marketing site https://yadaguru.wixsite.com/mysite please give me feedback.

**Comment by wyantb** [comment]
Quick note: on FireFox, the images don't display properly: ![marketingsiteff](https://cloud.githubusercontent.com/assets/726818/23107119/54c8f732-f6c5-11e6-9558-c2d6e831f815.png)

Otherwise, in general I think it looks great!  I have some thoughts on some things that might be tweaked to make it even better.
* The header on the site looks a little off compared to the header of the app (especially since the logo is missing), and the Code for Philly logo doesn't look all that great on a blue background.  It's a funny example (pulled from http://www.wordstream.com/blog/ws/2014/10/20/call-to-action-examples ), but compare how Manpacks does their call to action: https://launch.manpacks.com/ - they've got a white header and action buttons, and below that there's a color change and the call to action.  I think you could do the same.
* Perhaps, instead of the call to action being "Try Me!", make it "Start Planning Now!".  I think the coloring of that button could be a little bit clearer that it's separate from the rest of the content around it, and it could afford to be twice the height and width.
* The section ```"Don't Let A Missed Document Deadline Kill your School Dreams"``` *really* feels like it should be a landmark itself, rather than bundled with the "WHAT" section.  Perhaps this section could be "WHY"?
* The section "Easy Setup", the text would benefit from some more padding between it and the phones to the left, I think
* Can you get rid of the WIX.com callouts?  Haha, they are a bit distracting, but no worries if that's a restriction of using them :)

**Comment by michiQ** [comment]
Awesome Feedback! Incorporated all of your suggestions.   Also I tried FF and it was ok - wonder if I was pushing at the same time. Can you try again?   Wix callouts will go away when we publish to our domain.  

Interested in your thoughts on the udpates.  Thanks!

**Comment by wyantb** [comment]
Looks great!  And it being funny on FF was, of course, my fault - ad blockers.  Shame on me :)

**Comment by michiQ** [comment]
Thanks again!  That  white header is a winner!

**Comment by bobderrico80** [comment]
@wyantb Great suggestions. This is looking really good!

**Comment by michiQ** [comment]
Suggested graphic to put on www.yadaguru.com (current legacy site) that when clicked will lead to about.yadaguru.com
![screen shot 2017-02-21 at 1 26 03 pm](https://cloud.githubusercontent.com/assets/8203279/23178716/7d7f165a-f839-11e6-998a-50b65bc5e6ca.png)

Suggested placement

![screen shot 2017-02-21 at 1 30 13 pm](https://cloud.githubusercontent.com/assets/8203279/23178828/d81b7608-f839-11e6-86af-9d985048184d.png)

**Comment by bobderrico80** [comment]
Looks good. Regarding placement, do you envision a fixed-position element (will stay put on the side of the screen as the user scrolls), or would it be able to be scrolled away?

**Comment by michiQ** [comment]
would prefer it stay there permanently.  Then we'll update it with a date as we get closer to that date.  But we need to post the marketing site to about.yadaguru.com first. Because the link from the graphic will go to the new marketing site.

**Comment by michiQ** [comment]
Gonna split this one up cause there's a lot of work here

**Comment by michiQ** [comment]
Subissues:
#158 -MIGRATION: Add notice button to Yadaguru.com
#159 - MIGRATION: Update Notice Button on Yadaguru.com to show the actual Migration Day
#160 - MIGRATION: Move to CFP AWS
#161 - MIGRATION: Move current site to Legacy.Yadaguru.com
#162 - MIGRATION: Update Yadaguru.com with Version 2
#163 - MIGRATION: Update Marketing site to point to Yadaguru.com
#164 - MIGRATION: Set up Twilio in the yadaguru@gmail.com account
