### ISSUE TITLE
QAM: Didn't get ASAP text messages

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#128]

**Comment by michiQ** [comment]
I've added new schools today and thought that the asap text messages would come through but as of yet, they haven't.  Could be on a schedule for later this evening?

**Comment by bobderrico80** [comment]
Hmmm.... for some reason I was thinking that ASAPs wouldn't get sent (because they are on or past the current date), so currently the sms sending service doesn't use these. If we want to do this, we probably want to fire those messages as soon as the school is created.

I wonder if we even need this though. If they are adding a school, they have the app open and are already there, so maybe sending an SMS isn't necessary.

The other messages (on QAM) should be sent around noon on the day they are due.

**Comment by michiQ** [comment]
yup that makes sense. Plus I'm going to probably just git rid of admin in the other ticket.  So I'm going to close this one.
