### ISSUE TITLE
QAM: 7/1/2017 reminders showing up on school due on 3/1/2017

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#132]
there are reminders showing  up on 7/1/2017 and I can't figure out why through admin

**Comment by michiQ** [comment]
there are reminders showing up on 7/1/2017 and I can't figure out why through admin

**Comment by bobderrico80** [comment]
It is the 'Summer' timeframe. It is set to an absolute date of 7/1/2017. This appears regardless of due date because it is not tied in any way to the school's due date.

This is a little tricky. We could code the app to not show any reminders after the school's due date. The issue with this is that we DO want 5/1/2017. We could just not send any messages after 5/1/2017, but I would rather not hard-code a date into the app code that we would have to play around with.

Maybe a better idea would be to remove the summer reminders for now, then then add them back in through the admin portal after May 1st?

**Comment by michiQ** [comment]
removed the summer stuff and this is now done
