### ISSUE TITLE
Directions and Rewording for Export Buttons

### ISSUE THREAD

**Issue by adobley** [yadaguru/yadaguru-app#42]
Export to ics especially does not mean much to most users.

Export buttons should be reworded to follow some consistency. These could be done in tandem with some of the UX improvements suggested in #39.

Instructions on how to import ics files into different applications via links to official FAQs and instructions for some of the calendar exports would prove valuable to users.

**Comment by michiQ** [comment]
Export now says Google Cal, ICal and Outlook.  We should add ICal Instructions to the FAQ page. However since we are focusing on text and don't think a lot of kids will use the cal functions, it's a lower prioirty to write the directions.  Google Cal currently works well.  Outlook is a future possibility and could be removed if we don't want to try and do that now.

**Comment by michiQ** [comment]
ux prototype - go to the calendar page to see https://live.uxpin.com/288d7fede09c9a3618e31be42b3e10a7de6cbdfd#/pages/30689783
