### ISSUE TITLE
Long-term idea: Get specific dates for popular schools

### ISSUE THREAD

**Issue by titlecharacter** [yadaguru/yadaguru-app#43]
Having a default "normal cadence" for schools works in general, but once there's some usage data, you can identify schools with a lot of applicants and grab hard official numbers for due-dates - plus filter out reminders for requirements that a particular school might not have. If a lot of students are applying to CCP/Temple/Drexel/Harvard, that's an opportunity to do a tiny bit of manual labor to supplement the smart defaults.

**Comment by michiQ** [comment]
YES! - that would be great.  I'm adding this one to the Rally backlog.  Then it could truly be a Phiiladelphia App!

**Comment by mikecasas** [comment]
What about having some type of schema so universities could create their own due dates and then upload them?

**Comment by michiQ** [comment]
So the issue is now that colleges only provide one date - the application date.  All the other dates that YadaGuru gives are dates that are derived from guidance couselors best practices about when something should be done.  For example, the school will publish 1/1/2016 as the date by which the application is due.  But they won't give the student the date by which that student should start asking thier teachers for recommendations.  Is those type of soft dates that students fail on.  They'll often just ask someone a week before 1/1/2016 and changes of them getting it to the school on on time are slim.  That's YadaGuru's value prop is that no one else is actually making it easy for student's to get those reminders.

**Comment by titlecharacter** [comment]
Ah, good point! Okay, so it's probably just one date. Still, it'd be nice
to have an option for a student to say "I'm applying to Temple for Fall
2016" and have their date(s) stored.

**Comment by michiQ** [comment]
Yes - Mike the idea is a great one - and I really love it.

**Comment by mikecasas** [comment]
Thanks for the clarification.
