### ISSUE TITLE
Content is cut off on small screens.

### ISSUE THREAD

**Issue by bobderrico80** [yadaguru/yadaguru-app#79]
I noticed when switching to iPhone 4 in chrome dev tools that parts of the UI are scrolled off and inaccessible. There seems to be an issue with overflow: hidden somewhere. Either scrolling needs to be allowed, or UI elements need to be scaled down on smaller screens (probably a combination of both)

**Comment by zgavin1** [comment]
Hmm @bobderrico80 looks like this is a bit older, could some of this maybe have been resolved already? The only instance of overflow I could find is on the "forget my number" modal here
![screen shot 2016-11-05 at 10 00 09 pm](https://cloud.githubusercontent.com/assets/9595970/20034841/a5ab78ca-a3a3-11e6-95ba-dae0c7d5a1b2.png)

**Comment by zgavin1** [comment]
Found some other examples. Maybe this requires a QA session to collect them? We could create either one big issue with a bunch pics of the instances where this occurs, or a bunch of specific issues for each view/state.

**Comment by michiQ** [comment]
yeah - found it as well in phone 6
![img_3506](https://cloud.githubusercontent.com/assets/8203279/20224200/4323ad78-a80b-11e6-9951-341639aad58f.jpg)

**Comment by wyantb** [comment]
Bob mentioned this as a possible first task to work on.  My preference, @zgavin1, would be to list out all the initial issues you've spotted in one place.  In the event there's a common cause, one fix could fix several of the problems.  And if there's no common cause, we can split later.  But for now it's most helpful just to have a consolidated list of problems to work through along with matching expectations.

**Comment by michiQ** [comment]
Hi @wyantb!  Not sure if Zack saw this or not, but there are a few places listed above.  Maybe you could start with those - they are highest priority. When you go through the app on your phone, especially the original onboarding process, you'll see the issue.  I don't think we have an issue once we are through onboarding.

**Comment by wyantb** [comment]
Got it.  If all the issues are part of one flow, that's enough info to go by.

**Comment by michiQ** [comment]
Cool. Thanks!

**Comment by zgavin1** [comment]
Hey yeah. There is just the one flow to really work through, and I do expect there to be certain fixes that hit more than one instance of these overflow issues. Haven't been through this in a while, though. I could probably find some time tomorrow to jump in.

**Comment by wyantb** [comment]
On small devices, height is the critical factor; a quick `@media (max-height: 600px)` and tightening up the margins of the onboarding header and `<p>` tags goes a long way to getting this working on more screens with little effort (see #125).

Additional questions, though: do you care about rotated screens?  An iPhone 5, for example, has a height of about 570 pixels.  A rotated iPhone 6, on the other hand, has a height of about 375 pixels.  What kind of real estate do you want to get functional here?

Separately, I notice that the menu bar items containing the "Logout" button - after the onboarding flow - get cutoff as well.  Phones do something with the pixel counts we give them that I'm not familiar with and will need to look into a bit more to get a decent non-JS solution.

**Comment by michiQ** [comment]
I like tightening up the margins - seems like a good lean idea, lots of bang with just a few changes. 

Honestly hadn't thought rotated at all and I just rotated and _realized we have a problem_  in that we don't have a scroll up or down on the onboarding screen so when we rotate, we cut off the bottom and there's no going forward!   Awesome find!

![img_3746](https://cloud.githubusercontent.com/assets/8203279/22405025/172e208a-e60a-11e6-9fed-26a093623f2a.jpg)

I'm going to open another issue for the rotated screen work and link it to this one.   Since kids can always rotate back to vertical, and since you're working on the vertical so we know that will look ok, (in other words, there's viable solution), I'll move it to the 'Thinking About Doing' column.   And if we find we have some more time, it can be picked up. 

Another thing I like doing is keeping the work in small batches with highest priority first.    That is how we got this far on all volunteer effort. 

I'm available though this or slack all day to look at changes as they come through if you want me to.  
:)  Fun fact, today is my daughter's 24th birthday.  She and my son and their friends are the reason I decided that kids need help with this process.  Here's that story   https://phillycollegeapps.wordpress.com/2016/08/13/who-we-are-and-why-we-do-what-we-do/

**Comment by bobderrico80** [comment]
Check out #129 and #130 as well. There is probably lots of smaller-screen tweaking that will need to be done across the app.

**Comment by bobderrico80** [comment]
@michiQ Merged in some awesome fixes by @wyantb. I did a relatively quick QA of his changes, and he addressed many issues... I didn't happen to run into any screen issues. This probably could use a more thorough QA before moving to done though, to make sure we got everything.

His changes have been deployed to both QA environments.

**Comment by michiQ** [comment]
i think the only remaining issue on this one is the calendar which we have #151 for.  So i'm going to close this one.  Thanks @wyantb !
