### ISSUE TITLE
Add non-touch controls for onboarding

### ISSUE THREAD

**Issue by bobderrico80** [yadaguru/yadaguru-app#89]
The onboarding view does not currently have a way to navigate through the slides without a touch screen. There needs to be an arrow at the bottom of the onboarding screen, that the user can click or tap on to advance the onboarding

**Comment by bobderrico80** [comment]
@lmdiby - Would you be able to mock this up?

**Comment by zgavin1** [comment]
Hmm this ticket is a bit more complicated. My first attempt was a simple markup solution, adding a next and back button to the onboarding view, but I quickly realized that this wont' solve the issue. There are cases where we want "Back" and "Submit" rather than "back" and "Next", etc. Also, the word "tap" is hardcoded into the markup in certain places which isn't a huge deal, but yeah.

**Comment by michiQ** [comment]
working on mockup

**Comment by michiQ** [comment]
OK folks - so UXPin has made some changes and now my prototype is fraught with issues (its been about seven months since I've been in.).  That said - here is my (fraught with issues) prototype with the new visual for the desktop folks to migrate through.  Let me know if youthink this would work  https://collaborate.uxpin.com/9b4ba59f29ab83a34a5d98f606f4696aab330b21#/pages/31898600
