### ISSUE TITLE
Security think

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#97]

**Comment by michiQ** [comment]
This one is about thinking about securing the text phone numbers.  We don't want anyone to hack us and get those numbers. I think we'll need to think about what we might have to do in December.  I take the lead on setting up a meet to talk about this.

**Comment by bobderrico** [comment]
I think an adequate solution would be to hash the phone numbers (like is usually done for passwords). This way, if someone was able to hack into the DB and get the list of users, there wouldn't be any readable information.

**Comment by michiQ** [comment]
that works!

**Comment by wyantb** [comment]
I took a quick crack at this, but I should call out one interesting bit: when websites (that know what they're doing) store passwords, they do three things.  1) Use a secure, one-way hashing alg meant for passwords (I believe the PR does this).  2) They use a global, per-app salt (the PR fakes this with SUPER_SECRET_SALT that should be replaced with an actual secret).  3) They use a *per row* salt.  We...can't actually do this since we have no separate username field.

Implementing parts 1 and 2 definitely help, though without a username / user lookup field independent of the phone number field, there is one layer of defense missing.  In a perfect world, part 3 means that even if an attacker gets the global salt, it's still computationally expensive to brute force collisions for each user we have.  Without that bit, if an attacker is able to grab our global salt value, then they can just loop over every phone number in existence and check for collisions.

**Comment by wyantb** [comment]
Honestly, though, I'm separating out this comment because I'm probably overthinking the above.  These are just phone numbers.  If an attacker wants to get phone numbers, they can pretty much just look in an address book.  In practice just hashing with a global secret salt should be just fine.

**Comment by bobderrico80** [comment]
I agree. I think avoiding storing the phone numbers in plain text should be fine for our case.

**Comment by michiQ** [comment]
just housekeeping. Moving this to closed because we had a good think and it turned into some great work.
